package com.demo1.models;
// Generated 27/04/2018 10:15:28 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int codigo;
     private String nombres;
     private String apellidos;
     private String escuela;
     private String dni;
     private String correo;
     private Set libroporAlumnos = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(int codigo) {
        this.codigo = codigo;
    }

    public Alumno(int codigo, String nombres, String apellidos, String escuela, String dni, String correo) {
        this.codigo = codigo;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.escuela = escuela;
        this.dni = dni;
        this.correo = correo;
    }
    
    
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(String escuela) {
        this.escuela = escuela;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set getLibroporAlumnos() {
        return this.libroporAlumnos;
    }
    
    public void setLibroporAlumnos(Set libroporAlumnos) {
        this.libroporAlumnos = libroporAlumnos;
    }




}


