package com.demo1.models;
// Generated 27/04/2018 10:15:28 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {

     private int idLibro;
     private String nombres;
     private String autor;
     private String editorial;
     private String publicacion;
     private Set libroporAlumnos = new HashSet(0);

    public Libro() {
    }

	
    public Libro(int idLibro) {
        this.idLibro = idLibro;
    }
    public Libro(int idLibro, String nombres, String autor, String editorial, String publicacion, Set libroporAlumnos) {
       this.idLibro = idLibro;
       this.nombres = nombres;
       this.autor = autor;
       this.editorial = editorial;
       this.publicacion = publicacion;
       this.libroporAlumnos = libroporAlumnos;
    }

    public Libro(int idLibro, String nombres, String autor, String editorial, String publicacion) {
        this.idLibro = idLibro;
        this.nombres = nombres;
        this.autor = autor;
        this.editorial = editorial;
        this.publicacion = publicacion;
    }
    
    
    
   
    public int getIdLibro() {
        return this.idLibro;
    }
    
    public void setIdLibro(int idLibro) {
        this.idLibro = idLibro;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getEditorial() {
        return this.editorial;
    }
    
    public void setEditorial(String editorial) {
        this.editorial = editorial;
    }
    public String getPublicacion() {
        return this.publicacion;
    }
    
    public void setPublicacion(String publicacion) {
        this.publicacion = publicacion;
    }
    public Set getLibroporAlumnos() {
        return this.libroporAlumnos;
    }
    
    public void setLibroporAlumnos(Set libroporAlumnos) {
        this.libroporAlumnos = libroporAlumnos;
    }




}


