package com.demo1.models;
// Generated 27/04/2018 10:15:28 AM by Hibernate Tools 4.3.1



/**
 * LibroporAlumno generated by hbm2java
 */
public class LibroporAlumno  implements java.io.Serializable {


     private int idLibroporAlumno;
     private Alumno alumno;
     private Libro libro;
     private Usuario usuario;

    public LibroporAlumno() {
    }

    public LibroporAlumno(int idLibroporAlumno, Alumno alumno, Libro libro, Usuario usuario) {
       this.idLibroporAlumno = idLibroporAlumno;
       this.alumno = alumno;
       this.libro = libro;
       this.usuario = usuario;
    }
   
    public int getIdLibroporAlumno() {
        return this.idLibroporAlumno;
    }
    
    public void setIdLibroporAlumno(int idLibroporAlumno) {
        this.idLibroporAlumno = idLibroporAlumno;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


