package com.demo1.models;
// Generated 27/04/2018 10:15:28 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String usuario;
     private String password;
     private String nombres;
     private String apellidos;
     private Set libroporAlumnos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario(int idUsuario, String usuario, String password, String nombres, String apellidos, Set libroporAlumnos) {
       this.idUsuario = idUsuario;
       this.usuario = usuario;
       this.password = password;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.libroporAlumnos = libroporAlumnos;
    }

    public Usuario(int idUsuario, String usuario, String password, String nombres, String apellidos) {
        this.idUsuario = idUsuario;
        this.usuario = usuario;
        this.password = password;
        this.nombres = nombres;
        this.apellidos = apellidos;
    }
    
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Set getLibroporAlumnos() {
        return this.libroporAlumnos;
    }
    
    public void setLibroporAlumnos(Set libroporAlumnos) {
        this.libroporAlumnos = libroporAlumnos;
    }




}


